name: Selenium Test

on:
  push:
    branches:
      - master

jobs:
  selenium:
    runs-on: windows-latest  # Cambiado a un entorno basado en Windows

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r Requirements.txt

      - name: Run Selenium tests
        env:
          USER: ${{ secrets.USER }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          chromedriver.exe  # Ejecutar chromedriver
          python3 Login.py





